name: movie
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #observable: any
  #dart_chromecast: 
   # git:
     # url: https://github.com/fastogt/dart_chromecast.git
    #  ref: master
  flutter_mdns_plugin: ^0.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.9
  dio_http_cache: ^0.2.5
  fish_redux: ^0.3.7
  common_utils: ^1.2.1
  path_provider: ^1.3.0
  shared_preferences: ^0.5.3+4
  palette_generator: ^0.2.0
  shimmer: ^1.0.1
  url_launcher: ^5.2.5
  chewie: ^0.12.2
  video_player: ^1.0.1
  youtube_player_flutter: ^7.0.0+7
  intl: ^0.17.0-nullsafety.2
  cached_network_image: ^2.0.0
  parallax_image: ^0.3.1+1
  flutter_staggered_grid_view: ^0.3.0
  collection: ^1.14.11
  photo_view: ^0.10.3
  toast: ^0.1.5
  permission_handler: ^3.2.2
  screenshot: ^0.1.1
  share_extend: ^1.0.9
  qr_flutter: ^2.1.0+55
  flutter_rating_bar: ^3.0.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.5.0
  flutter_inappwebview: ^4.0.0
  flutter_cache_manager: ^1.1.3
  image_picker: ^0.6.7+2
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.2.0
  firebase_storage: ^3.1.3 
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  firebase_admob: ^0.9.3+1
  firebase_ml_vision: ^0.9.4
  lottie: ^0.4.0+1
  package_info: ^0.4.0+16
  flutter_downloader: ^1.5.0
  flutter_braintree: ^0.6.0
  camera: ^0.5.8+2
  flutter_local_notifications: ^1.4.4+1
  graphql_flutter: ^3.0.1
  stripe_payment: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  - images/
  - lib/models/country_phone_codes.json
  - appconfig.json
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
